import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AdminSideBar from "@/components/AdminSideBar";
import AdminBottomBar from "@/components/AdminBottomBar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin: boolean = true;
  return (
    // <StoreProvider>
    <html lang="en">
      <ToastContainer
        position="top-right"
        autoClose={1000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
          {isAdmin && <AdminSideBar />}
          {children}
        </div>
        {isAdmin && <AdminBottomBar />}
      </body>
    </html>
  );
}
